---
# tasks file for tomcat
- name: Install Java
  ansible.builtin.yum:
     name: java
     state: installed
- name: Download the Tomcat Package
  ansible.builtin.get_url:
      url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz"
      dest: /opt/
      mode: '0755'
- name: Untar the tomcat File
  ansible.builtin.unarchive:
     src: /opt/apache-tomcat-9.0.71.tar.gz
     dest: /opt/
     remote_src: yes
- name: Chnage the Permision of the tomcat File
  ansible.builtin.file:
     path: /opt/apache-tomcat-9.0.71
     mode: '0755'
     recurse: yes
     state: directory
- name: Ansible Templete for tomcat-users.xml
  ansible.builtin.template:
    src: tomcat-users.xml.j2
    dest: /opt/apache-tomcat-9.0.71/conf/tomcat-users.xml
    remote_src: false
    mode: '0640'
    owner: root
    group: root
    backup: yes
- name: Ansible Templete For Context.xml
  ansible.builtin.template:
    src: context.xml.j2 
    dest: /opt/apache-tomcat-9.0.71/webapps/manager/META-INF/context.xml
    remote_src: false
    mode: '0640'
    owner: root
    group: root
    backup: yes
- name: download  Artifact from the nexus
  ansible.builtin.get_url:
    url: "http://35.154.204.15:8081/repository/sample/in/javahome/simple-app/1.0.0/simple-app-1.0.0.war"
    username: admin
    password: admin
    dest: /opt/apache-tomcat-9.0.71/webapps/
    remote_src: yes
  notify: restart the tomcat server
